---
    - name: create tmp directory
      file: dest=/tmp/dcos state=directory

    - name: install dependencies
      yum: name={{ item  }} state=present
      with_items:
        - unzip
        - ipset
        - ntp

    - name: enable ntpd
      service: name=ntpd state=started enabled=yes    

    - name: add group nogroup
      group: name=nogroup state=present

    - name: disable selinux
      selinux: state=disabled

    - name: restart host
      shell: sleep 1;/usr/sbin/reboot
      async: 1
      poll: 0
      ignore_errors: true

    - name: waiting for host to come back online
      local_action: wait_for host={{ inventory_hostname }} search_regex=OpenSSH port=22 timeout=300 state=started

    - name: Add docker repository
      yum_repository:
        name: dockerrepo
        description: Docker Respository
        baseurl: https://yum.dockerproject.org/repo/main/centos/$releasever/
        state: present
        enabled: yes
        gpgcheck: yes
        gpgkey: https://yum.dockerproject.org/gpg

    - pause: seconds=1

    - name: install docker
      yum: name=docker-engine-1.11.2 state=present

    - name: copy docker config for overlayfs
      copy: src=files/docker.service dest=/usr/lib/systemd/system

    - name: reload sytemd
      command: /usr/bin/systemctl daemon-reload

    - name: start docker
      service: name=docker state=started

# following needs to have serial: 2
    - name: fetch installer from bootstrap
      get_url: url=http://{{ bootstrap_public_ip }}:{{ bootstrap_public_port }}/dcos_install.sh dest=/tmp/dcos mode="u=rwx,g=rwx,o=rwx" 

# configure master nodes

    - name: install dcos on master
      command: bash dcos_install.sh master
      args:
        chdir: /tmp/dcos
